services:
  api:
    build:
      context: .
      network: host
    ports:
      - "8000:8000"
    environment:
      AHNLICH_HOST: ahnlich
      AHNLICH_PORT: 1370
      USE_AHNLICH: "true"
      AHNLICH_STORE_NAME: "legal_docs"
    volumes:
      - .:/app
    command: fastapi dev --entrypoint app.main:app --host 0.0.0.0 --port 8000

  ahnlich_db:
    image: ghcr.io/deven96/ahnlich-db:latest
    entrypoint: ["ahnlich-db"]
    command: ["run", "--host", "0.0.0.0", "--port", "1369"]
    ports:
      - "1369:1369"

  ahnlich:
    image: ghcr.io/deven96/ahnlich-ai:latest
    entrypoint: ["ahnlich-ai"]
    command:
      [
        "run",
        "--host",
        "0.0.0.0",
        "--port",
        "1370",
        "--db-host",
        "ahnlich_db",
        "--db-port",
        "1369",
      ]
    ports:
      - "1370:1370"
    depends_on:
      - ahnlich_db
